# This is just here so the system can start up.
# The real configuration will be specific to each app that consumes this library.
site:
  name: 'Development SixCRM'
  domain: 'sixcrm.com'
  include_stage: true

#Technical Debt:  This sort of thing needs to be strongly protected
jwt:
  issuer: 'https://development-api.sixcrm.com'
  site:
    secret_key: 'pO9HJmVXzTOagNP-xW9Es8-s0HGQt28hqlvAPJx6e6rHeryvnyBGDn-LJn_80XdV'
    domain: ''
    expiration: 3600
  transaction:
    secret_key: 'ashdaiuwdaw9d0u197f02ji9ujoja90juahwi'
    expiration: 3600
  customer:
    secret_key: 'a0d0wa9du8hucioj==12jr0cuvcamcq9ij1k3nfnkjIh(UH(8hjnciqihuyBGDn-LJn_80XdV'
    domain: ''
    expiration: 3600
