aws:
  region: 'us-east-1'
  account: '821071795213'

#Technical Debt:  This sort of thing should be encrypted...
jwt:
  issuer: 'https://staging-api.sixcrm.com'
  development_bypass: 'deathstalker'
  site: #This is the key for all graph requests (AKA Six users)
    secret_key: 'pO9HJmVXzTOagNP-xW9Es8-s0HGQt28hqlvAPJx6e6rHeryvnyBGDn-LJn_80XdV'
    domain: ''
    expiration: 3600
  transaction: #This is the key for the transactional endpoint requests (AKA non-Six users...)
    secret_key: 'ashdaiuwdaw9d0u197f02ji9ujoja90juahwi'
    expiration: 3600
  #Technical Debt:  The site key may be deprecated...
  site_key: 'anwdadawdjaklwdlakd'

dynamodb:
  endpoint: ''

sqs:
  deadletter_postfix: '_deadletter'
  max_receive_count: 5

cloudsearch:
  domainname: 'sixcrm'

#Technical Debt:  Let's eliminate this.
lambda:
  endpoint: ''
  function_names:
    deliveredtoarchive: 'sixtransaction-staging-archivedelivered'
    shippedtodelivered: 'sixtransaction-staging-confirmdelivery'
    pendingtoshipped: 'sixtransaction-staging-confirmshipped'
    pendingfailedtopending: 'sixtransaction-staging-shipproduct'
    holdtopending: 'sixtransaction-staging-shipproduct'
    holdtoarchive: 'sixtransaction-staging-archivehold'
    billtohold: 'sixtransaction-staging-processbilling'
    recovertohold: 'sixtransaction-staging-processbilling'
    createrebillstoarchive: 'sixtransaction-staging-createrebills'
    recovertoarchive: 'sixtransaction-staging-archiverecover'
    indextoarchive: 'sixtransaction-staging-indexentities'
    forwardmessage_deliveredtoarchive: 'sixtransaction-staging-deliveredtoarchive'
    forwardmessage_shippedtodelivered: 'sixtransaction-staging-shippedtodelivered'
    forwardmessage_pendingtoshipped: 'sixtransaction-staging-pendingtoshipped'
    forwardmessage_pendingfailedtopending: 'sixtransaction-staging-pendingfailedtopending'
    forwardmessage_holdtopending: 'sixtransaction-staging-holdtopending'
    forwardmessage_holdtoarchive: 'sixtransaction-staging-holdtoarchive'
    forwardmessage_billtohold: 'sixtransaction-staging-billtohold'
    forwardmessage_recovertohold: 'sixtransaction-staging-recovertohold'
    forwardmessage_createrebillstoarchive: 'sixtransaction-staging-rebilltoarchive'
    forwardmessage_recovertoarchive: 'sixtransaction-staging-recovertoarchive'
    forwardmessage_indextoarchive: 'sixtransaction-staging-indextoarchive'

shipping_providers:
  usps:
    user_id: '005SIXCR2114'
    password: '392VM80MW850'

#Technical Debt: This all needs to be configured elsewhere?
#Technical Debt:  Username and Password combinations need to be encrypted...

redshift:
  user: 'admin'
  #Technical Debt:  This is inappropriate
  database: 'dev'
  password: 'Jagodica9'
  #Technical Debt:  This needs to be in Environment Config
  host: 'sixcrm.ceigagt6gafq.us-east-1.redshift.amazonaws.com'
  port: 5439
  max: 10
  idle_timeout: 30000
  randomdata:
    staging_bucket: 'sixcrm-staging-redshift/sixcrm-random-generator'
    interval: 15768000 #this is provided in seconds

notifications:
  apn:
    token_key: ''
    token_key_id: ''
    token_team_id: ''
    production: false

#Technical Debt:  Down the road, we may have numerous caching strategies and we will need to be able to configure them dynamically
cache:
  usecache: 1
  cachebuster: 'somerandomthing1'

elasticache:
  max_attempts: 3
  retry_time: 1800000
  endpoint: '52.44.119.23'
  port: 6379
  default_expiration: 300

logging:
  loglevel: 0

kinesis:
  firehose:
    streams:
      transactions: 'six-staging-transactions'
      transaction_stream:
        DeliveryStreamName: 'six-staging-transactions'
        RedshiftDestinationConfiguration:
          ClusterJDBCURL: 'jdbc:redshift://sixcrm.ceigagt6gafq.us-east-1.redshift.amazonaws.com:5439/dev'
          CopyCommand:
            DataTableName: 'f_transactions'
            CopyOptions: "json 'auto' timeformat 'YYYY-MM-DDTHH:MI:SS'"
          Password: 'Jagodica9'
          RoleARN: 'arn:aws:iam::821071795213:role/sixcrm_kinesis_firehose_delivery_role'
          S3Configuration:
            BucketARN: 'arn:aws:s3:::sixcrm-staging-redshift'
            RoleARN: 'arn:aws:iam::821071795213:role/sixcrm_kinesis_firehose_delivery_role'
            BufferingHints:
              IntervalInSeconds: 60
              SizeInMBs: 1
            CompressionFormat: 'UNCOMPRESSED'
            Prefix: 'sixcrm-kinesis-transactions/'
          Username: 'admin'
          RetryOptions:
            DurationInSeconds: 1
          S3BackupMode: 'Disabled'
      events: 'six-staging-events'
      event_stream:
        DeliveryStreamName: 'six-staging-events'
        RedshiftDestinationConfiguration:
          ClusterJDBCURL: 'jdbc:redshift://sixcrm.ceigagt6gafq.us-east-1.redshift.amazonaws.com:5439/dev'
          CopyCommand:
            DataTableName: 'f_events'
            CopyOptions: "json 'auto' timeformat 'YYYY-MM-DDTHH:MI:SS'"
          Password: 'Jagodica9'
          RoleARN: 'arn:aws:iam::821071795213:role/sixcrm_kinesis_firehose_delivery_role'
          S3Configuration:
            BucketARN: 'arn:aws:s3:::sixcrm-staging-redshift'
            RoleARN: 'arn:aws:iam::821071795213:role/sixcrm_kinesis_firehose_delivery_role'
            BufferingHints:
              IntervalInSeconds: 60
              SizeInMBs: 1
            CompressionFormat: 'UNCOMPRESSED'
            Prefix: 'sixcrm-kinesis-events/'
          Username: 'admin'
          RetryOptions:
            DurationInSeconds: 1
          S3BackupMode: 'Disabled'
      activity: 'six-staging-activity'
      activity_stream:
        DeliveryStreamName: 'six-staging-activity'
        RedshiftDestinationConfiguration:
          ClusterJDBCURL: 'jdbc:redshift://sixcrm.ceigagt6gafq.us-east-1.redshift.amazonaws.com:5439/dev'
          CopyCommand:
            DataTableName: 'f_events'
            CopyOptions: "json 'auto' timeformat 'YYYY-MM-DDTHH:MI:SS'"
          Password: 'Jagodica9'
          RoleARN: 'arn:aws:iam::821071795213:role/sixcrm_kinesis_firehose_delivery_role'
          S3Configuration:
            BucketARN: 'arn:aws:s3:::sixcrm-staging-redshift'
            RoleARN: 'arn:aws:iam::821071795213:role/sixcrm_kinesis_firehose_delivery_role'
            BufferingHints:
              IntervalInSeconds: 60
              SizeInMBs: 1
            CompressionFormat: 'UNCOMPRESSED'
            Prefix: 'sixcrm-kinesis-activity/'
          Username: 'admin'
          RetryOptions:
            DurationInSeconds: 1
          S3BackupMode: 'Disabled'
