site:
  name: 'Recursix'
  domain: 'recursix.com'
  include_stage: false

serverless:
  verbose: 1

data_encryption:
  secret_key: '0ca75fc5b11c6ea70f57b6581c67e15c26dac751c5b6b1f94ab7ef4252d60dd3'

aws:
  region: 'us-east-1'
  account: '500031165490'

lambda:
  security_group: 'SixCRM-PrivateSubnet'
  subnets:
    - sixcrm-private1
    - sixcrm-private2
    - sixcrm-private3

elasticsearch:
  domain_name: 'sixcrm-logs'
  index_name: 'cloudwatch-logs'

s3:
  account_resources_bucket: 'account-resources'

sts:
  deployment_role_name: 'SixCRMDeployment'

ses:
  hostname: email-smtp.us-east-1.amazonaws.com
  port: 465
  username: 'ses-smtp-user.20180515-201240'
  smtp_username: AKIAJZTJ2IREWIAH7NDQ
  smtp_password: AvDRyLRWbVih3E+J6zoRrQBVuB7PMjPYrkqEeFC7dr0V
  default_sender_email: 'info@recursix.com'
  default_sender_name: 'Recursix'

#Technical Debt:  This sort of thing needs to be strongly protected
jwt:
  issuer: 'https://api.sixcrm.com'
  site: #This is the key for all graph requests (AKA Six users)
    secret_key: '3BH6LG7iu0_uATCPSi19ShFxif7IonGGIQEDr35kRIHpFdzMPzcD5_F2v0KlFTYd'
    domain: ''
    expiration: 3600
  transaction: #This is the key for the transactional endpoint requests (AKA non-Six users...)
    secret_key: 'z85t6nusfb3hafwnpw57pmdbnr9t9z5jmhjpv'
    expiration: 3600
    domain: ''
  customer:
    secret_key: 'BRQxG$6%5TtxpCYGE&v7yY@r%Yy%FhnETSB#uVH@keTeFNu*7vY&#vTH&#Q9w!268S&EgjkKE'
    domain: ''
    expiration: 3600

sqs:
  deadletter_postfix: '_deadletter'
  max_receive_count: 5

cloudsearch:
  domainname: 'sixcrm'

#Technical Debt:  Username and Password combinations need to be encrypted...
aurora:
  release: 9
  default_cluster_identifier: 'sixcrm'
  user: 'root'
  database: 'postgres'
  password: 'Jagodica9'
  port: 5440
  max: 10
  idle_timeout: 30000
  #Technical Debt:  Remove
  randomdata:
    interval: 300

notifications:
  apn:
    token_key: ''
    token_key_id: ''
    token_team_id: ''
    production: false

slack:
  channels:
    - channel: '#lambdas'
      kms_encrypted_hook_url: 'AQECAHj80T7Kli3v5wZmKcPbVFGj7MRHdpLvshzuP2ZIJ3vvjgAAAKcwgaQGCSqGSIb3DQEHBqCBljCBkwIBADCBjQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyN9XeW0Dk18ZFGQkYCARCAYL6U9hWmdM7Nz+yL0I78O5CU2FPHpzj3/o9yQmpsVaBuSztYipLnam5mlwbfx7mn5cKn8xNyTOD3WGfondnCsVsGyeIVIJJMZs1RWYW3ix18FukLP54LZXctfadN2CcvPQ=='
    - channel: '#servererrors'
      webhook_url: https://hooks.slack.com/services/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

tokenization:
  tokenex:
    id: 9615102903256758
    api_key: UAESYJ8HeIfmmGeg2qNS7l4dPFTYNlLA6t7zX4hF
    base: https://api.tokenex.com

aeg-limelight-api:
  throttleInSeconds: 2
  timeout: 30000
  membershipApiUrl: "https://{0}/admin/membership.php"
  transactionApiUrl: "https://{0}/admin/transaction.php"
