site:
  name: 'Development SixCRM'
  domain: 'sixcrm.com'
  include_stage: true

serverless:
  verbose: 3

data_encryption:
  secret_key: 'c6b1249c8e92e30811a6f85e41125469a84d2352be82692af663c1810da77c44'

aws:
  region: 'us-east-1'
  account: '068070110666'

lambda:
  security_groups:
    - sg-d7fdaa9e
  subnets:
    - subnet-db0ee887
    - subnet-fdf4079a
    - subnet-5b6c8c75

elasticsearch:
  domain_name: 'sixcrm-logs'
  index_name: 'cloudwatch-logs'

s3:
  account_resources_bucket: 'account-resources'

sts:
  deployment_role_name: 'SixCRMDeployment'

ses:
  hostname: email-smtp.us-east-1.amazonaws.com
  port: 465
  username: 'ses-smtp-user.20170828-134442'
  smtp_username: 'AKIAJEYLHSMCFIJYFMXQ'
  smtp_password: 'AhiiqjfmaJ9M2fD3zhzbjt17Da6xkOpYD2b1bkiovvrm'
  default_sender_email: 'info@development.sixcrm.com'
  default_sender_name: 'Development SixCRM'

#Technical Debt:  This sort of thing needs to be strongly protected
jwt:
  issuer: 'https://development-api.sixcrm.com'
  site:
    secret_key: 'J-LR3RIOxrHIe-MH-NftFYr7VFTB8xO8W8T451s35hJ0-V55aGdUQGCl1hGZ1OG1'
    domain: ''
    expiration: 3600
  transaction:
    secret_key: 'z85t6nusfb3hafwnpw57pmdbnr9t9z5jmhjpv'
    expiration: 3600
  customer:
    secret_key: 'BRQxG$6%5TtxpCYGE&v7yY@r%Yy%FhnETSB#uVH@keTeFNu*7vY&#vTH&#Q9w!268S&EgjkKE'
    domain: ''
    expiration: 3600

sqs:
  deadletter_postfix: '_deadletter'
  max_receive_count: 5

cloudsearch:
  domainname: 'sixcrm'
  endpoint: 'doc-sixcrm-x5xewjrr254yjyrln4mlvxvfm4.us-east-1.cloudsearch.amazonaws.com'

aurora:
  user: 'root'
  database: 'postgres'
  password: 'Jagodica9'
  host: development-aurora.sixcrm.com
  port: 5440
  max: 10
  idle_timeout: 30000
  randomdata:
    interval: 300

notifications:
  apn:
    token_key: ''
    token_key_id: ''
    token_team_id: ''
    production: false

slack:
  channels:
    - channel: '#lambdas'
      kms_encrypted_hook_url: 'AQECAHj80T7Kli3v5wZmKcPbVFGj7MRHdpLvshzuP2ZIJ3vvjgAAAKcwgaQGCSqGSIb3DQEHBqCBljCBkwIBADCBjQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyN9XeW0Dk18ZFGQkYCARCAYL6U9hWmdM7Nz+yL0I78O5CU2FPHpzj3/o9yQmpsVaBuSztYipLnam5mlwbfx7mn5cKn8xNyTOD3WGfondnCsVsGyeIVIJJMZs1RWYW3ix18FukLP54LZXctfadN2CcvPQ=='
    - channel: '#servererrors'
      webhook_url: https://hooks.slack.com/services/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

tokenization:
  tokenex:
    id: 2029633460477211
    api_key: XnIOBNQVmQRyfRMiQdA5FuQBalGDDTxWlgoJBL8N
    base: https://test-api.tokenex.com

aeg-limelight-api:
  throttleInSeconds: 2
  timeout: 30000
  membershipApiUrl: "https://{0}/admin/membership.php"
  transactionApiUrl: "https://{0}/admin/transaction.php"

shippo:
  apiKey: 'shippo_live_f61dc0a5715bb648fb81dbd23dcaa2c75da9f372'
