site:
  name: 'Local SixCRM'
  domain: 'sixcrm.com'
  include_stage: true

serverless:
  verbose: 2

data_encryption:
  secret_key: 'c6b1249c8e92e30811a6f85e41125469a84d2352be82692af663c1810da77c44'

aws:
  region: 'us-east-1'
  account: ''

lambda:
  region: 'localhost'
  security_group: 'SixCRM-PrivateSubnet'
  subnets:
    - sixcrm-private1
    - sixcrm-private2
    - sixcrm-private3

elasticsearch:
  domain_name: 'sixcrm-logs'
  index_name: 'cloudwatch-logs'

s3:
  account_resources_bucket: 'account-resources'

sts:
  deployment_role_name: 'SixCRMDeployment'

ses:
  hostname: email-smtp.us-east-1.amazonaws.com
  port: 465
  username: 'ses-smtp-user.20170828-134442'
  smtp_username: 'AKIAJEYLHSMCFIJYFMXQ'
  smtp_password: 'AhiiqjfmaJ9M2fD3zhzbjt17Da6xkOpYD2b1bkiovvrm'
  default_sender_email: 'info@development.sixcrm.com'
  default_sender_name: 'Development SixCRM'

#Technical Debt:  This sort of thing needs to be strongly protected
jwt:
  issuer: 'https://api.sixcrm.com'
  site:
    secret_key: 'J-LR3RIOxrHIe-MH-NftFYr7VFTB8xO8W8T451s35hJ0-V55aGdUQGCl1hGZ1OG1'
    domain: ''
    expiration: 3600
  transaction:
    secret_key: 'z85t6nusfb3hafwnpw57pmdbnr9t9z5jmhjpv'
    expiration: 3600
    domain: ''
  customer:
    secret_key: 'BRQxG$6%5TtxpCYGE&v7yY@r%Yy%FhnETSB#uVH@keTeFNu*7vY&#vTH&#Q9w!268S&EgjkKE'
    domain: ''
    expiration: 3600

dynamodb:
  region: 'localhost'
  endpoint: http://local-docker:8000

sqs:
  region: 'localhost'
  deadletter_postfix: '_deadletter'
  max_receive_count: 5
  endpoint: http://local-docker:9324

sns:
  region: 'localhost'
  endpoint: http://local-docker:9911

cloudsearch:
  domainname: 'sixcrm'
  domainendpoint: 'local-docker:15808'

aurora:
  release: 10
  region: 'localhost'
  user: 'postgres'
  database: 'postgres'
  password: ''
  host: local-docker
  port: 5440
  max: 10
  idle_timeout: 3000
  randomdata:
    interval: 300

notifications:
  apn:
    token_key: ''
    token_key_id: ''
    token_team_id: ''
    production: false

slack:
  channels:
    - channel: '#lambdas'
      kms_encrypted_hook_url: 'AQECAHj80T7Kli3v5wZmKcPbVFGj7MRHdpLvshzuP2ZIJ3vvjgAAAKcwgaQGCSqGSIb3DQEHBqCBljCBkwIBADCBjQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyN9XeW0Dk18ZFGQkYCARCAYL6U9hWmdM7Nz+yL0I78O5CU2FPHpzj3/o9yQmpsVaBuSztYipLnam5mlwbfx7mn5cKn8xNyTOD3WGfondnCsVsGyeIVIJJMZs1RWYW3ix18FukLP54LZXctfadN2CcvPQ=='
    - channel: '#servererrors'
      webhook_url: https://hooks.slack.com/services/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

tokenization:
  tokenex:
    id: 2029633460477211
    api_key: XnIOBNQVmQRyfRMiQdA5FuQBalGDDTxWlgoJBL8N
    base: https://test-api.tokenex.com

aeg-limelight-api:
  throttleInSeconds: 2
  timeout: 30000
  membershipApiUrl: "https://{0}/admin/membership.php"
  transactionApiUrl: "https://{0}/admin/transaction.php"

shippo:
  apiKey: 'shippo_test_230ff62035f444db3dac50171f0042656ac3fc34'
