development:
  aws_account_id: '068070110666'
  branch_name: 'development'
sandbox:
  aws_account_id: '909647584680'
staging:
  aws_account_id: '821071795213'
  branch_name: 'staging'
production:
  aws_account_id: '181111172466'
  branch_name: 'production'
priority:
  aws_account_id: '500031165490'
  branch_name: 'priority'
offline:
  local: true
docker:
  local: true
circle:
  local: true
