#Todo:
# Eliminate writes to S3 for the last successful build.  Use cache instead

defaults: &job-defaults
  docker:
    - image: circleci/node:8.10
      environment:
        - TZ: "/usr/share/zoneinfo/America/Los_Angeles"

version: 2
jobs:
  build:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: echo //registry.npmjs.org/:_authToken=$NPM_TOKEN >> ~/.npmrc && yarn install --frozen-lockfile
      - run:
          name: compile
          command: yarn run compile
      - save_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/sixcrm/node_modules
            - packages/sixcrm-platform/node_modules
            - packages/sixcrm-data/node_modules
            - packages/sixcrm-product-setup/node_modules
            - packages/sixcrm-subscriptions/node_modules
            - packages/sixcrm-orders/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - packages/sixcrm/lib
            - packages/sixcrm-platform/lib
            - packages/sixcrm-data/lib
            - packages/sixcrm-product-setup/lib
            - packages/sixcrm-subscriptions/lib
            - packages/sixcrm-orders/lib
  lint:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: 'Lint'
          command: yarn run lint
  unit_tests:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: 'Legacy Unit Tests (JavaScript)'
          command: stage=circle yarn run test-unit-circle
      - run:
          name: 'Legacy Unit Tests (TypeScript)'
          command: stage=circle yarn run ts-test
  product_setup_tests:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.15.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Start Aurora Docker Image
          command: |
            set -x
            cd packages/sixcrm-product-setup && docker-compose up -d
      - run:
          name: Wait for Docker
          command: echo "Pausing to allow docker to catch up..." && sleep 15
      - run:
          name: Aurora Create Tables
          command: cd packages/sixcrm-product-setup && docker-compose run -v /home/circleci/project:/sixcrmserverless -w /sixcrmserverless/packages/sixcrm -e CIRCLECI -e SIX_VERBOSE -e stage=circle node node ./deployment/aurora/deploy-schema.js
      - run:
          name: Product Setup Tests
          command: cd packages/sixcrm-product-setup && docker-compose run -v /home/circleci/project:/sixcrmserverless -w /sixcrmserverless/packages/sixcrm-product-setup -e CIRCLECI -e SIX_VERBOSE -e stage=circle node yarn run test-productsetup
      - run:
          name: Subscription Tests
          command: cd packages/sixcrm-subscriptions && docker-compose run -v /home/circleci/project:/sixcrmserverless -w /sixcrmserverless/packages/sixcrm-subscriptions -e CIRCLECI -e SIX_VERBOSE -e stage=circle node yarn run test-subscriptions
  pre_deploy:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: debugging
          command: printenv
      - run:
          name: Set Access Credentials
          command: mkdir -p deployment_credentials/
      - run:
          name: Create Credentials
          command: cd packages/sixcrm && SIX_VERBOSE=2 && node ./deployment/sts/create_role_commands.js --branch=$CIRCLE_BRANCH --output=../../deployment_credentials/stscredentials
      - persist_to_workspace:
          root: .
          paths:
            - deployment_credentials
      - run:
          name: set credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Debugging 2
          command: printenv
  backup_datastore:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Backup DynamoDB
          command: cd packages/sixcrm && export SIX_VERBOSE=2 && printenv && node ./deployment/dynamodb/backup_tables.js --branch=$CIRCLE_BRANCH --version=$CIRCLE_SHA1
  deploy_serverless:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Serverless Deploy
          command: cd packages/sixcrm && SLS_DEBUG=* npx serverless deploy --stage $CIRCLE_BRANCH
      - run:
          name: Deploy Step Function State Machines
          command: cd packages/sixcrm && export SIX_VERBOSE=2 && node ./deployment/stepfunctions/deploy_state_machines.js
      - run:
          name: Cloudwatch Log Subscriptions
          command: cd packages/sixcrm && export SIX_VERBOSE=2 && node ./deployment/cloudwatch/deploy_subscription_filters.js
  deploy_aurora:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: Setup SSH Tunnel
          command: |
            cd packages/sixcrm
            echo "Host *" >> ~/.ssh/config
            echo "   AddressFamily inet" >> ~/.ssh/config
            ssh -o StrictHostKeyChecking=no -f -N -L5440:$CIRCLE_BRANCH-aurora.sixcrm.com:5440 ec2-user@$CIRCLE_BRANCH-bastion.sixcrm.com
      - run:
          name: Aurora Create Tables
          command: cd packages/sixcrm && SIX_VERBOSE=2 AURORA_PROXY=true node ./deployment/aurora/deploy-schema.js
  #Eh... not very useful currently
  environment_test:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Entity Integration Tests
          command: SIX_VERBOSE=2 yarn run test-environment
  seed:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Entity Seed
          command: cd packages/sixcrm && SIX_VERBOSE=2 node ./deployment/dynamodb/deploy_seeds.js
      - run:
          name: Entity Live Seed
          command: cd packages/sixcrm && SIX_VERBOSE=2 node ./deployment/dynamodb/deploy_live_seeds.js
  deleteblock_integration_tests:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Deleteblock Integration Tests
          command: yarn run test-deleteblocks
  entity_integration_tests:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Entity Integration Tests
          command: yarn run test-entities
  analytics_integration_tests:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Analytics Integration Tests
          command: SIX_VERBOSE=2 yarn run test-integration-analytics
  transactional_integration_tests:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Transactional Integration Tests
          command: SIX_VERBOSE=6 yarn run test-transactions

workflows:
  version: 2
  build_deploy_test:
    jobs:
      - build
      - lint:
          requires:
            - build
          filters:
            branches:
              ignore:
                - staging
                - production
                - priority
      - unit_tests:
          requires:
            - build
          filters:
            branches:
              ignore:
                - staging
                - production
                - priority
      - product_setup_tests:
          requires:
            - build
          filters:
            branches:
              ignore:
                - staging
                - production
                - priority
      - pre_deploy:
          requires:
            - lint
            - unit_tests
            - product_setup_tests
          filters:
            branches:
              only:
                - development
                - staging
                - production
                - priority
      - backup_datastore:
          requires:
            - pre_deploy
          filters:
            branches:
              only:
                - staging
                - production
                - priority
      - deploy_aurora:
          requires:
            - pre_deploy
            - backup_datastore
          filters:
            branches:
              only:
                - development
                - staging
                - production
                - priority
      - deploy_serverless:
          requires:
            - deploy_aurora
          filters:
            branches:
              only:
                - development
                - staging
                - production
                - priority
      - environment_test:
          requires:
            - deploy_serverless
          filters:
            branches:
              only:
                - development
                - staging
                - production
                - priority
#      - seed:
#          requires:
#            - environment_test
#          filters:
#            branches:
#              only:
#                - development
#                - staging
#                - production
#                - priority
      - entity_integration_tests:
          requires:
            - environment_test
          filters:
            branches:
              only:
                - development
                - staging
                - production
                - priority
      - deleteblock_integration_tests:
          requires:
            - environment_test
          filters:
            branches:
              only:
                - development
                - staging
                - production
                - priority
      - analytics_integration_tests:
          requires:
            - environment_test
          filters:
            branches:
              only:
                - development
                - staging
                - production
                - priority
      - transactional_integration_tests:
          requires:
            - environment_test
          filters:
            branches:
              only:
                - development
                - staging
                - production
                - priority
