#Todo:
# Eliminate writes to S3 for the last successful build.  Use cache instead
# Increase the level of parallelism
# Add Blue/Green for Production

functional_tests_default: &functional-tests-default
  machine: true

defaults: &job-defaults
  docker:
    - image: circleci/node:7.10.0
      environment:
        - TZ: "/usr/share/zoneinfo/America/Los_Angeles"

version: 2
jobs:
  pre:
    <<: *job-defaults
    steps:
      - run: sudo npm install -g npm@latest
  build:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: 'Lint'
          command: npm run lint
  unit_tests:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: 'Unit Tests'
          command: npm run test-unit
  functional_tests:
    <<: *functional-tests-default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Start Docker Cluster
          command: |
            set -x
            docker-compose --file tools/docker/docker-compose.yml up -d
      - run: echo "Pausing to allow Redshift to catch up..." && sleep 30
      - run:
          name: Execute Functional Connectivity Test
          command: npm run test-functional-connectivity
      - run:
          name: Deploy Local Dynamo
          command: SIX_VERBOSE=2 stage=local node ./deployment/dynamodb/deploy_tables.js
      - run:
          name: Deploy Local SQS
          command: SIX_VERBOSE=2 stage=local node ./deployment/sqs/deploy_queues.js
#      - run:
#          name: Seed Local Dynamo
#          command: SIX_VERBOSE=2 stage=local node ./deployment/dynamodb/deploy_seeds.js
      - run:
          name: Execute State Machine Tests In Docker
          command: SIX_VERBOSE=0 stage=local npm run test-functional-state-machine-docker
  pre_deploy:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: debugging
          command: printenv
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Access Credentials
          command: mkdir -p deployment_credentials/
      - run:
          name: Create Credentials
          command: SIX_VERBOSE=2 && node ./deployment/sts/create_role_commands.js --branch=$CIRCLE_BRANCH --output=deployment_credentials/stscredentials
      - save_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
          paths:
            - deployment_credentials
      - run:
          name: set credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Debugging 2
          command: printenv
  backup_datastore:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Backup DynamoDB
          command:  printenv && node ./deployment/dynamodb/backup_tables.js --branch=$CIRCLE_BRANCH --version=$CIRCLE_SHA1
      - run:
          name: Backup Redshift
          command:  node ./deployment/redshift/backup_cluster.js --branch=$CIRCLE_BRANCH --version=$CIRCLE_SHA1
  deploy_serverless:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Serveless Deploy
          command: node ./node_modules/serverless/bin/serverless deploy --stage $CIRCLE_BRANCH
  deploy_security_groups:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: EC2 Security Groups
          command: node ./deployment/ec2/deploy_security_groups.js
  deploy_s3:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: S3 Buckets
          command: node ./deployment/s3/deploy_buckets.js || echo "No changes, skipping."
      - run:
          name: S3 Backups
          command: node ./deployment/s3/deploy_backups.js || echo "No changes, skipping."
  deploy_sqs:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: SQS
          command: ./tools/changesInDirectory.sh deployment/sqs && node ./deployment/sqs/deploy_queues.js || echo "No changes, skipping."
  deploy_elasticache:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Elasticache
          command: ./tools/changesInDirectory.sh deployment/elasticache && node ./deployment/elasticache/deploy.js || echo "No changes, skipping."
  deploy_iam:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: IAM Deploy Roles
          command: node ./deployment/iam/destroy_roles.js && node ./deployment/iam/deploy_roles.js
  deploy_dynamodb:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: DynamoDB Deploy Tables
          command: ./tools/changesInDirectory.sh deployment/dynamodb/configuration/tables && node ./deployment/dynamodb/deploy_tables.js || echo "No changes, skipping."
      - run:
          name: DynamoDB Autoscale Tables
          command: ./tools/changesInDirectory.sh deployment/dynamodb/configuration/autoscaling && node ./deployment/dynamodb/deploy_autoscaling.js || echo "No changes, skipping."
  deploy_redshift:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Redshift Create Cluster
          command: ./tools/changesInDirectory.sh deployment/redshift && node ./deployment/redshift/deploy_cluster.js && node ./deployment/redshift/seed_referential.js || echo "No changes, skipping."
      - run:
          name: Redshift Create Tables
          command: ./tools/changesInDirectory.sh deployment/redshift && node ./deployment/redshift/deploy_tables.js && echo "Pausing to allow queries to complete..." && sleep 240 || echo "No changes, skipping."
  deploy_kinesis:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Kinesis Deploy
          command: node ./deployment/kinesis/deploy_streams.js || echo "No changes, skipping."
  post_deployment:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Save Last Commit
          command: node deployment/circle/save_last_commit.js
      - run:
          name: AWS Services Available
          command: ./tools/changesInDirectory.sh deployment/redshift && echo "Pausing to allow queries to complete..." && sleep 240 || echo "No changes, skipping."
  #Eh... not very useful currently
  purge:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: SQS Purge
          command: node ./deployment/sqs/purge_queues.js
#      - run:
#          name: Cloudsearch Purge
#          command: node ./deployment/cloudsearch/purge.js
      - run:
          name: Elasticache Purge
          command: node ./deployment/elasticache/purge.js
#     - run:
#         name: DynamoDB Purge
#         command: node ./deployment/dynamodb/purge_tables.js
  seed:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Entity Seed
          command: ./tools/changesInDirectory.sh deployment/dynamodb/configuration/seeds && node ./deployment/dynamodb/deploy_seeds.js || echo "No changes, skipping."
  deleteblock_integration_tests:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Deleteblock Integration Tests
          command: npm run test-deleteblocks
  entity_integration_tests:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Entity Integration Tests
          command: npm run test-entities
  analytics_integration_tests:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Analytics Integration Tests
          command: npm run test-analytics
  transactional_integration_tests:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Transactional Integration Tests
          command: export SIX_VERBOSE=2; npm run test-transactions
  synchronize_index:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: deployment-credentials-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Set Credentials
          command: cat deployment_credentials/stscredentials >> $BASH_ENV
      - run:
          name: Synchronize Search Index With DynamoDB
          command: node helper/searchindexfix.js --fix=true
  merge:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Merge To Upper
          command: |
            if [ "${CIRCLE_BRANCH}" == "development" ]; then
              ./deployment/utilities/merge_branches.sh development staging
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
              ./deployment/utilities/merge_branches.sh staging production
            fi

workflows:
  version: 2
  build_deploy_test_and_merge:
    jobs:
      - pre:
          filters:
            branches:
              only:
                - development
                - staging
                - production
      - build:
          requires:
            - pre
      - lint:
          requires:
            - build
          filters:
            branches:
              only:
                - development
      - unit_tests:
          requires:
            - build
          filters:
            branches:
              only:
                - development
      - functional_tests:
          requires:
            - build
          filters:
            branches:
              only:
                - development
      - pre_deploy:
          requires:
            - build
            - lint
            - unit_tests
      - backup_datastore:
          requires:
            - pre_deploy
          filters:
            branches:
              ignore:
                - development
      - deploy_serverless:
          requires:
            - pre_deploy
            - lint
            - unit_tests
            - backup_datastore
      - deploy_security_groups:
          requires:
            - pre_deploy
            - lint
            - unit_tests
            - backup_datastore
      - deploy_iam:
          requires:
            - pre_deploy
            - lint
            - unit_tests
            - backup_datastore
      - deploy_s3:
          requires:
            - pre_deploy
            - lint
            - unit_tests
            - backup_datastore
      - deploy_sqs:
          requires:
            - deploy_security_groups
            - deploy_iam
      - deploy_elasticache:
          requires:
            - deploy_security_groups
            - deploy_iam
      - deploy_dynamodb:
          requires:
            - deploy_security_groups
            - deploy_iam
      - deploy_redshift:
          requires:
            - deploy_security_groups
            - deploy_iam
      - deploy_kinesis:
          requires:
            - deploy_redshift
      - post_deployment:
          requires:
            - deploy_serverless
            - deploy_security_groups
            - deploy_s3
            - deploy_sqs
            - deploy_elasticache
            - deploy_iam
            - deploy_dynamodb
            - deploy_redshift
            - deploy_kinesis
      - seed:
          requires:
            - post_deployment
      - entity_integration_tests:
          requires:
            - seed
      - deleteblock_integration_tests:
          requires:
            - seed
      - analytics_integration_tests:
          requires:
            - seed
      - transactional_integration_tests:
          requires:
            - seed
      - synchronize_index:
          requires:
             - transactional_integration_tests
             - entity_integration_tests
             - deleteblock_integration_tests
             - analytics_integration_tests
      - hold:
          type: approval
          requires:
             - transactional_integration_tests
             - entity_integration_tests
             - deleteblock_integration_tests
             - analytics_integration_tests
          filters:
            branches:
              only:
                - production
      - merge:
          requires:
            - hold
            - transactional_integration_tests
            - entity_integration_tests
            - deleteblock_integration_tests
            - analytics_integration_tests
          filters:
            branches:
              ignore:
                - production
