jwt:
  issuer: 'https://api.sixcrm.com'
  development_bypass: 'deathstalker'
  site: #This is the key for all graph requests (AKA Six users)
    secret_key: 'pO9HJmVXzTOagNP-xW9Es8-s0HGQt28hqlvAPJx6e6rHeryvnyBGDn-LJn_80XdV'
    domain: ''
    expiration: 3600
  transaction: #This is the key for the transactional endpoint requests (AKA non-Six users...)
    secret_key: 'ashdaiuwdaw9d0u197f02ji9ujoja90juahwi'
    expiration: 3600
  #Technical Debt:  The site key may be deprecated...
  site_key: 'anwdadawdjaklwdlakd'

dynamodb:
  endpoint: ''

lambda:
  endpoint: ''
  function_names:
    deliveredtoarchive: 'sixtransaction-development-archivedelivered'
    shippedtodelivered: 'sixtransaction-development-confirmdelivery'
    pendingtoshipped: 'sixtransaction-development-confirmshipped'
    pendingfailedtopending: 'sixtransaction-development-shipproduct'
    holdtopending: 'sixtransaction-development-shipproduct'
    holdtoarchive: 'sixtransaction-development-archivehold'
    billtohold: 'sixtransaction-development-processbilling'
    recovertohold: 'sixtransaction-development-processbilling'
    createrebillstoarchive: 'sixtransaction-development-createrebills'
    recovertoarchive: 'sixtransaction-development-archiverecover'
    indextoarchive: 'sixtransaction-development-indexentities'
    forwardmessage_deliveredtoarchive: 'sixtransaction-development-deliveredtoarchive'
    forwardmessage_shippedtodelivered: 'sixtransaction-development-shippedtodelivered'
    forwardmessage_pendingtoshipped: 'sixtransaction-development-pendingtoshipped'
    forwardmessage_pendingfailedtopending: 'sixtransaction-development-pendingfailedtopending'
    forwardmessage_holdtopending: 'sixtransaction-development-holdtopending'
    forwardmessage_holdtoarchive: 'sixtransaction-development-holdtoarchive'
    forwardmessage_billtohold: 'sixtransaction-development-billtohold'
    forwardmessage_recovertohold: 'sixtransaction-development-recovertohold'
    forwardmessage_createrebillstoarchive: 'sixtransaction-development-rebilltoarchive'
    forwardmessage_recovertoarchive: 'sixtransaction-development-recovertoarchive'
    forwardmessage_indextoarchive: 'sixtransaction-development-indextoarchive'

shipping_providers:
  usps:
    user_id: '005SIXCR2114'
    password: '392VM80MW850'

redshift:
  user: 'admin'
  database: 'dev'
  password: 'Jagodica9'
  host: 'sixcrm-test.ch9ptr45aofu.us-east-1.redshift.amazonaws.com'
  port: 5439
  max: 10
  idleTimeoutMillis: 30000
  cluster:
    cluster_identifier: 'sixcrm-development'
    node_type: 'dc1.large'
    automated_snapshot_retention_period: 3
    cluster_type: 'single-node'
    publicly_accessible: true
    skip_final_cluster_snapshot: true
    final_cluster_snapshot_identifier: ''
  randomdata:
    staging_bucket: 'sixcrm-development-redshift/sixcrm-random-generator'
    interval: 15768000 #this is provided in seconds

notifications:
  apn:
    token_key: ''
    token_key_id: ''
    token_team_id: ''
    production: false

#Technical Debt:  Down the road, we may have numerous caching strategies and we will need to be able to configure them dynamically
cache:
  usecache: 1
  cachebuster: 'somerandomthing1'

elasticache:
  max_attempts: 3
  retry_time: 1800000
  endpoint: '34.204.230.178'
  port: 6379

logging:
  loglevel: 0

kinesis:
  firehose:
    streams:
      transactions: 'six-development-transactions'
      transaction_stream:
        DeliveryStreamName: 'six-development-transactions'
        RedshiftDestinationConfiguration:
          ClusterJDBCURL: 'jdbc:redshift://sixcrm-test.ch9ptr45aofu.us-east-1.redshift.amazonaws.com:5439/dev'
          CopyCommand:
            DataTableName: 'f_transactions'
            CopyOptions: "json 'auto' timeformat 'YYYY-MM-DDTHH:MI:SS'"
          Password: 'Jagodica9'
          RoleARN: 'arn:aws:iam::068070110666:role/firehose_delivery_role'
          S3Configuration:
            BucketARN: 'arn:aws:s3:::sixcrm-development-redshift'
            RoleARN: 'arn:aws:iam::068070110666:role/firehose_delivery_role'
            BufferingHints:
              IntervalInSeconds: 60
              SizeInMBs: 1
            CompressionFormat: 'UNCOMPRESSED'
            Prefix: 'sixcrm-kinesis-transactions/'
          Username: 'admin'
          RetryOptions:
            DurationInSeconds: 1
          S3BackupMode: 'Disabled'
      sessions: 'six-development-sessions'
      sessions_stream:
        DeliveryStreamName: 'six-development-sessions'
        RedshiftDestinationConfiguration:
          ClusterJDBCURL: 'jdbc:redshift://sixcrm-test.ch9ptr45aofu.us-east-1.redshift.amazonaws.com:5439/dev'
          CopyCommand:
            DataTableName: 'f_sessions'
            CopyOptions: "json 'auto' timeformat 'YYYY-MM-DDTHH:MI:SS'"
          Password: 'Jagodica9'
          RoleARN: 'arn:aws:iam::068070110666:role/firehose_delivery_role'
          S3Configuration:
            BucketARN: 'arn:aws:s3:::sixcrm-development-redshift'
            RoleARN: 'arn:aws:iam::068070110666:role/firehose_delivery_role'
            BufferingHints:
              IntervalInSeconds: 60
              SizeInMBs: 1
            CompressionFormat: 'UNCOMPRESSED'
            Prefix: 'sixcrm-kinesis-transactions/'
          Username: 'admin'
          RetryOptions:
            DurationInSeconds: 1
          S3BackupMode: 'Disabled'
      events: 'six-development-events'
      event_stream:
        DeliveryStreamName: 'six-development-events'
        RedshiftDestinationConfiguration:
          ClusterJDBCURL: 'jdbc:redshift://sixcrm-test.ch9ptr45aofu.us-east-1.redshift.amazonaws.com:5439/dev'
          CopyCommand:
            DataTableName: 'f_events'
            CopyOptions: "json 'auto' timeformat 'YYYY-MM-DDTHH:MI:SS'"
          Password: 'Jagodica9'
          RoleARN: 'arn:aws:iam::068070110666:role/firehose_delivery_role'
          S3Configuration:
            BucketARN: 'arn:aws:s3:::sixcrm-development-redshift'
            RoleARN: 'arn:aws:iam::068070110666:role/firehose_delivery_role'
            BufferingHints:
              IntervalInSeconds: 60
              SizeInMBs: 1
            CompressionFormat: 'UNCOMPRESSED'
            Prefix: 'sixcrm-kinesis-events/'
          Username: 'admin'
          RetryOptions:
            DurationInSeconds: 1
          S3BackupMode: 'Disabled'
      activity: 'six-development-activity'
      activity_stream:
        DeliveryStreamName: 'six-development-activity'
        RedshiftDestinationConfiguration:
          ClusterJDBCURL: 'jdbc:redshift://sixcrm-test.ch9ptr45aofu.us-east-1.redshift.amazonaws.com:5439/dev'
          CopyCommand:
            DataTableName: 'f_events'
            CopyOptions: "json 'auto' timeformat 'YYYY-MM-DDTHH:MI:SS'"
          Password: 'Jagodica9'
          RoleARN: 'arn:aws:iam::068070110666:role/firehose_delivery_role'
          S3Configuration:
            BucketARN: 'arn:aws:s3:::sixcrm-development-redshift'
            RoleARN: 'arn:aws:iam::068070110666:role/firehose_delivery_role'
            BufferingHints:
              IntervalInSeconds: 60
              SizeInMBs: 1
            CompressionFormat: 'UNCOMPRESSED'
            Prefix: 'sixcrm-kinesis-activity/'
          Username: 'admin'
          RetryOptions:
            DurationInSeconds: 1
          S3BackupMode: 'Disabled'

aws:
  region: 'us-east-1'
  account: '068070110666'

s3:
  redshift:
    buckets:
      bucketRedshift:
        bucket: 'sixcrm-development-redshift'
        folders:
          folder1: 'sixcrm-kinesis-activity/'
          folder2: 'sixcrm-kinesis-events/'
          folder3: 'sixcrm-kinesis-merchant-processor/'
          folder4: 'sixcrm-kinesis-transactions/'
          folder5: 'sixcrm-manual-upload/'
          folder6: 'sixcrm-output/'
          folder7: 'sixcrm-random-generator/'
          folder8: 'sixcrm-resources/'
          folder9: 'sixcrm-test/'
