jwt:
  issuer: 'https://api.sixcrm.com'
  development_bypass: 'deathstalker'
  site: #This is the key for all graph requests (AKA Six users)
    secret_key: 'pO9HJmVXzTOagNP-xW9Es8-s0HGQt28hqlvAPJx6e6rHeryvnyBGDn-LJn_80XdV'
    domain: ''
    expiration: 3600
  transaction: #This is the key for the transactional endpoint requests (AKA non-Six users...)
    secret_key: 'ashdaiuwdaw9d0u197f02ji9ujoja90juahwi'
    expiration: 3600
  #Technical Debt:  The site key may be deprecated...
  site_key: 'anwdadawdjaklwdlakd'

dynamodb:
  endpoint: ''

lambda:
  endpoint: ''
  function_names:
    deliveredtoarchive: 'sixtransaction-development-archivedelivered'
    shippedtodelivered: 'sixtransaction-development-confirmdelivery'
    pendingtoshipped: 'sixtransaction-development-confirmshipped'
    pendingfailedtopending: 'sixtransaction-development-shipproduct'
    holdtopending: 'sixtransaction-development-shipproduct'
    holdtoarchive: 'sixtransaction-development-archivehold'
    billtohold: 'sixtransaction-development-processbilling'
    recovertohold: 'sixtransaction-development-processbilling'
    createrebillstoarchive: 'sixtransaction-development-createrebills'
    recovertoarchive: 'sixtransaction-development-archiverecover'
    indextoarchive: 'sixtransaction-development-indexentities'
    forwardmessage_deliveredtoarchive: 'sixtransaction-development-deliveredtoarchive'
    forwardmessage_shippedtodelivered: 'sixtransaction-development-shippedtodelivered'
    forwardmessage_pendingtoshipped: 'sixtransaction-development-pendingtoshipped'
    forwardmessage_pendingfailedtopending: 'sixtransaction-development-pendingfailedtopending'
    forwardmessage_holdtopending: 'sixtransaction-development-holdtopending'
    forwardmessage_holdtoarchive: 'sixtransaction-development-holdtoarchive'
    forwardmessage_billtohold: 'sixtransaction-development-billtohold'
    forwardmessage_recovertohold: 'sixtransaction-development-recovertohold'
    forwardmessage_createrebillstoarchive: 'sixtransaction-development-rebilltoarchive'
    forwardmessage_recovertoarchive: 'sixtransaction-development-recovertoarchive'
    forwardmessage_indextoarchive: 'sixtransaction-development-indextoarchive'

sqs:
  bill_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-bill'
  bill_failed_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-bill-failed'
  recover_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-recover'
  hold_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-hold'
  pending_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-pending'
  pending_failed_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-pending-failed'
  shipped_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-shipped'
  delivered_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-delivered'
  rebill_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-rebill'
  rebill_failed_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-rebill-failure'
  search_indexing_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-searchindex'
  bill_deadletter_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-bill_deadletter'
  bill_failed_deadletter_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-bill-failed_deadletter'
  recover_deadletter_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-recover_deadletter'
  hold_deadletter_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-hold_deadletter'
  pending_deadletter_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-pending_deadletter'
  pending_failed_deadletter_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-pending-failed_deadletter'
  shipped_deadletter_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-shipped_deadletter'
  delivered_deadletter_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-delivered_deadletter'
  rebill_deadletter_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-rebill_deadletter'
  rebill_failed_deadletter_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-rebill-failure_deadletter'
  search_indexing_deadletter_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-searchindex_deadletter'

nmi:
  username: 'demo'
  password: 'password'
  endpoint: 'https://secure.networkmerchants.com/api/transact.php'

shipping_providers:
  usps:
    user_id: '005SIXCR2114'
    password: '392VM80MW850'

redshift:
  user: 'admin'
  database: 'dev'
  password: 'Jagodica9'
  host: 'sixcrm-test.ch9ptr45aofu.us-east-1.redshift.amazonaws.com'
  port: 5439
  max: 10
  idleTimeoutMillis: 30000
  deployment:
    cluster_identifier: 'sixcrm-development'
    node_type: 'dc1.large'
    automated_snapshot_retention_period: 3
    cluster_type: 'single-node'
    publicly_accessible: true
    master_username: 'admin'
    master_user_password: 'Jagodica9'
    d_b_name: 'dev'
  randomdata:
    staging_bucket: 'sixcrm-development-redshift/sixcrm-random-generator'
    interval: 300 #this is provided in seconds

notifications:
  apn:
    token_key: ''
    token_key_id: ''
    token_team_id: ''
    production: false

#Technical Debt:  Down the road, we may have numerous caching strategies and we will need to be able to configure them dynamically
cache:
  usecache: 1
  cachebuster: 'somerandomthing1'

elasticache:
  max_attempts: 3
  retry_time: 1800000
  endpoint: '34.204.230.178'
  port: 6379

logging:
  loglevel: 0

kinesis:
  firehose:
    streams:
      transactions: 'six-development-transactions'
      events: 'six-development-events'
      activity: 'six-development-activity'

aws:
  region: 'us-east-1'
