aws:
  region: 'us-east-1'
  account: '068070110666'

jwt:
  issuer: 'https://development-api.sixcrm.com'
  development_bypass: 'deathstalker'
  site: #This is the key for all graph requests (AKA Six users)
    secret_key: 'pO9HJmVXzTOagNP-xW9Es8-s0HGQt28hqlvAPJx6e6rHeryvnyBGDn-LJn_80XdV'
    domain: ''
    expiration: 3600
  transaction: #This is the key for the transactional endpoint requests (AKA non-Six users...)
    secret_key: 'ashdaiuwdaw9d0u197f02ji9ujoja90juahwi'
    expiration: 3600
  #Technical Debt:  The site key may be deprecated...
  site_key: 'anwdadawdjaklwdlakd'

dynamodb:
  endpoint: ''

sqs:
  deadletter_postfix: '_deadletter'
  max_receive_count: 5

#Technical Debt:  Can't we configure this?
cloudsearch:
  domainname: 'sixcrm'

#Technical Debt:  Eliminate Configurations....
lambda:
  endpoint: ''
  function_names:
    deliveredtoarchive: 'sixtransaction-development-archivedelivered'
    shippedtodelivered: 'sixtransaction-development-confirmdelivery'
    pendingtoshipped: 'sixtransaction-development-confirmshipped'
    pendingfailedtopending: 'sixtransaction-development-shipproduct'
    holdtopending: 'sixtransaction-development-shipproduct'
    holdtoarchive: 'sixtransaction-development-archivehold'
    billtohold: 'sixtransaction-development-processbilling'
    recovertohold: 'sixtransaction-development-processbilling'
    createrebillstoarchive: 'sixtransaction-development-createrebills'
    recovertoarchive: 'sixtransaction-development-archiverecover'
    indextoarchive: 'sixtransaction-development-indexentities'
    forwardmessage_deliveredtoarchive: 'sixtransaction-development-deliveredtoarchive'
    forwardmessage_shippedtodelivered: 'sixtransaction-development-shippedtodelivered'
    forwardmessage_pendingtoshipped: 'sixtransaction-development-pendingtoshipped'
    forwardmessage_pendingfailedtopending: 'sixtransaction-development-pendingfailedtopending'
    forwardmessage_holdtopending: 'sixtransaction-development-holdtopending'
    forwardmessage_holdtoarchive: 'sixtransaction-development-holdtoarchive'
    forwardmessage_billtohold: 'sixtransaction-development-billtohold'
    forwardmessage_recovertohold: 'sixtransaction-development-recovertohold'
    forwardmessage_createrebillstoarchive: 'sixtransaction-development-rebilltoarchive'
    forwardmessage_recovertoarchive: 'sixtransaction-development-recovertoarchive'
    forwardmessage_indextoarchive: 'sixtransaction-development-indextoarchive'

shipping_providers:
  usps:
    user_id: '005SIXCR2114'
    password: '392VM80MW850'

redshift:
  user: 'admin'
  database: 'dev'
  password: 'Jagodica9'
  host: 'sixcrm-development.ch9ptr45aofu.us-east-1.redshift.amazonaws.com'
  port: 5439
  max: 10
  idle_timeout: 30000
  randomdata:
    #Technical Debt:  This wont work in environments other than development
    staging_bucket: 'sixcrm-development-redshift/sixcrm-random-generator'
    interval: 15768000 #this is provided in seconds

notifications:
  apn:
    token_key: ''
    token_key_id: ''
    token_team_id: ''
    production: false

cache:
  usecache: 1
  cachebuster: 'somerandomthing1'

elasticache:
  max_attempts: 3
  retry_time: 1800000
  endpoint: '34.204.230.178'
  port: 6379
  default_expiration: 300

logging:
  loglevel: 0

#Technical Debt:  Remove
#Taking this out of site.yml config
kinesis:
  firehose:
    streams:
      transactions: 'six-development-transactions-t'
      transaction_stream:
        DeliveryStreamName: 'six-development-transactions'
        RedshiftDestinationConfiguration:
          ClusterJDBCURL: ''
          CopyCommand:
            DataTableName: 'f_transactions'
            CopyOptions: "json 'auto' timeformat 'YYYY-MM-DDTHH:MI:SS'"
          Password: 'Jagodica9'
          RoleARN: 'sixcrm_kinesis_firehose_delivery_role'
          S3Configuration:
            BucketARN: 'arn:aws:s3:::sixcrm-development-redshift'
            RoleARN: 'sixcrm_kinesis_firehose_delivery_role'
            BufferingHints:
              IntervalInSeconds: 60
              SizeInMBs: 1
            CompressionFormat: 'UNCOMPRESSED'
            Prefix: 'sixcrm-kinesis-transactions/'
          Username: 'admin'
          RetryOptions:
            DurationInSeconds: 1
          S3BackupMode: 'Disabled'
      sessions: 'six-development-sessions'
      sessions_stream:
        DeliveryStreamName: 'six-development-sessions'
        RedshiftDestinationConfiguration:
          ClusterJDBCURL: ''
          CopyCommand:
            DataTableName: 'f_sessions'
            CopyOptions: "json 'auto' timeformat 'YYYY-MM-DDTHH:MI:SS'"
          Password: 'Jagodica9'
          RoleARN: 'sixcrm_kinesis_firehose_delivery_role'
          S3Configuration:
            BucketARN: 'arn:aws:s3:::sixcrm-development-redshift'
            RoleARN: 'sixcrm_kinesis_firehose_delivery_role'
            BufferingHints:
              IntervalInSeconds: 60
              SizeInMBs: 1
            CompressionFormat: 'UNCOMPRESSED'
            Prefix: 'sixcrm-kinesis-transactions/'
          Username: 'admin'
          RetryOptions:
            DurationInSeconds: 1
          S3BackupMode: 'Disabled'
      events: 'six-development-events'
      event_stream:
        DeliveryStreamName: 'six-development-events'
        RedshiftDestinationConfiguration:
          ClusterJDBCURL: ''
          CopyCommand:
            DataTableName: 'f_events'
            CopyOptions: "json 'auto' timeformat 'YYYY-MM-DDTHH:MI:SS'"
          Password: 'Jagodica9'
          RoleARN: 'sixcrm_kinesis_firehose_delivery_role'
          S3Configuration:
            BucketARN: 'arn:aws:s3:::sixcrm-development-redshift'
            RoleARN: 'sixcrm_kinesis_firehose_delivery_role'
            BufferingHints:
              IntervalInSeconds: 60
              SizeInMBs: 1
            CompressionFormat: 'UNCOMPRESSED'
            Prefix: 'sixcrm-kinesis-events/'
          Username: 'admin'
          RetryOptions:
            DurationInSeconds: 1
          S3BackupMode: 'Disabled'
      activity: 'six-development-activity'
      activity_stream:
        DeliveryStreamName: 'six-development-activity'
        RedshiftDestinationConfiguration:
          ClusterJDBCURL: ''
          CopyCommand:
            DataTableName: 'f_events'
            CopyOptions: "json 'auto' timeformat 'YYYY-MM-DDTHH:MI:SS'"
          Password: 'Jagodica9'
          RoleARN: 'sixcrm_kinesis_firehose_delivery_role'
          S3Configuration:
            BucketARN: 'arn:aws:s3:::sixcrm-development-redshift'
            RoleARN: 'sixcrm_kinesis_firehose_delivery_role'
            BufferingHints:
              IntervalInSeconds: 60
              SizeInMBs: 1
            CompressionFormat: 'UNCOMPRESSED'
            Prefix: 'sixcrm-kinesis-activity/'
          Username: 'admin'
          RetryOptions:
            DurationInSeconds: 1
          S3BackupMode: 'Disabled'
