aws:
  region: 'us-east-1'
  account: '068070110666'

ses:
  hostname: email-smtp.us-east-1.amazonaws.com
  port: 465
  username: 'ses-smtp-user.20170828-134442'
  smtp_username: 'AKIAJEYLHSMCFIJYFMXQ'
  smtp_password: 'AhiiqjfmaJ9M2fD3zhzbjt17Da6xkOpYD2b1bkiovvrm'
  default_sender_email: 'info@development.sixcrm.com'
  default_sender_name: 'Development SixCRM'

jwt:
  issuer: 'https://development-api.sixcrm.com'
  site:
    secret_key: 'pO9HJmVXzTOagNP-xW9Es8-s0HGQt28hqlvAPJx6e6rHeryvnyBGDn-LJn_80XdV'
    domain: ''
    expiration: 3600
  transaction:
    secret_key: 'ashdaiuwdaw9d0u197f02ji9ujoja90juahwi'
    expiration: 3600

dynamodb:
  endpoint: ''

sqs:
  deadletter_postfix: '_deadletter'
  max_receive_count: 5

cloudsearch:
  domainname: 'sixcrm'

lambda:
  endpoint: ''
  function_names:
    deliveredtoarchive: 'archivedelivered'
    shippedtodelivered: 'confirmdelivery'
    pendingtoshipped: 'confirmshipped'
    pendingfailedtopending: 'shipproduct'
    holdtopending: 'shipproduct'
    holdtoarchive: 'archivehold'
    billtohold: 'processbilling'
    recovertohold: 'processbilling'
    createrebillstoarchive: 'createrebills'
    recovertoarchive: 'archiverecover'
    indextoarchive: 'indexentities'
    sendnotificationstoarchive: 'sendnotifications'
    forwardmessage_deliveredtoarchive: 'deliveredtoarchive'
    forwardmessage_shippedtodelivered: 'shippedtodelivered'
    forwardmessage_pendingtoshipped: 'pendingtoshipped'
    forwardmessage_pendingfailedtopending: 'pendingfailedtopending'
    forwardmessage_holdtopending: 'holdtopending'
    forwardmessage_holdtoarchive: 'holdtoarchive'
    forwardmessage_billtohold: 'billtohold'
    forwardmessage_recovertohold: 'recovertohold'
    forwardmessage_createrebillstoarchive: 'rebilltoarchive'
    forwardmessage_indextoarchive: 'indextoarchive'
    forwardmessage_sendnotificationstoarchive: 'sendnotificationstoarchive'
    forwardmessage_recovertoarchive: 'recovertoarchive'

redshift:
  user: 'admin'
  database: 'analytics'
  password: 'Jagodica9'
  port: 5439
  max: 10
  idle_timeout: 30000
  randomdata:
    interval: 300

notifications:
  apn:
    token_key: ''
    token_key_id: ''
    token_team_id: ''
    production: false

cache:
  usecache: 1
  cachebuster: 'somerandomthing12'

elasticache:
  max_attempts: 3
  retry_time: 1800000
  endpoint: '34.204.230.178'
  port: 6379
  default_expiration: 300

logging:
  loglevel: 0

slack:
  channels:
    - channel: '#lambdas'
      kms_encrypted_hook_url: 'AQECAHj80T7Kli3v5wZmKcPbVFGj7MRHdpLvshzuP2ZIJ3vvjgAAAKcwgaQGCSqGSIb3DQEHBqCBljCBkwIBADCBjQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyN9XeW0Dk18ZFGQkYCARCAYL6U9hWmdM7Nz+yL0I78O5CU2FPHpzj3/o9yQmpsVaBuSztYipLnam5mlwbfx7mn5cKn8xNyTOD3WGfondnCsVsGyeIVIJJMZs1RWYW3ix18FukLP54LZXctfadN2CcvPQ=='
    - channel: '#servererrors'
      webhook_url: https://hooks.slack.com/services/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
