jwt:
  transaction_key: 'ashdaiuwdaw9d0u197f02ji9ujoja90juahwi'
  site_key: 'anwdadawdjaklwdlakd'
  development_bypass: 'deathstalker'
  auth0: 
    secret_key: 'pO9HJmVXzTOagNP-xW9Es8-s0HGQt28hqlvAPJx6e6rHeryvnyBGDn-LJn_80XdV'
    domain: ''
  
dynamodb:
  access_keys_table: 'access_keys'
  sessions_table: 'sessions'
  transactions_table: 'transactions'
  rebills_table: 'rebills'
  customers_table: 'customers'
  products_table: 'products'
  credit_cards_table: 'credit_cards'
  users_table: 'users'
  user_acls_table: 'useracls'
  loadbalancers_table: 'loadbalancers'
  product_schedules_table: 'product_schedules'
  affiliates_table: 'affiliates'
  campaigns_table: 'campaigns' 
  merchant_providers_table: 'merchant_providers'
  fulfillment_providers_table: 'fulfillment_providers'
  email_templates_table: 'email_templates'
  smtp_providers_table: 'smtp_providers'
  shipping_receipts_table: 'shipping_receipts'
  accounts_table: 'accounts'
  roles_table: 'roles'
  ses_notifications_table: 'ses_notifications'
  endpoint: ''
  
lambda:
  endpoint: ''
  function_names:
    deliveredtoarchive: 'sixtransaction-development-archivedelivered'
    shippedtodelivered: 'sixtransaction-development-confirmdelivery'
    pendingtoshipped: 'sixtransaction-development-confirmshipped'
    pendingfailedtopending: 'sixtransaction-development-shipproduct'
    holdtopending: 'sixtransaction-development-shipproduct'
    holdtoarchive: 'sixtransaction-development-archivehold'
    billtohold: 'sixtransaction-development-processbilling'
    recovertohold: 'sixtransaction-development-processbilling'
    createrebillstoarchive: 'sixtransaction-development-createrebills'
    recovertoarchive: 'sixtransaction-development-archiverecover'
    indextoarchive: 'sixtransaction-development-indexentities'
    
sqs:
  bill_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-bill'
  bill_failed_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-bill-failed'
  recover_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-recover'
  hold_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-hold'
  pending_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-pending'
  pending_failed_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-pending-failed'
  shipped_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-shipped'
  delivered_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-delivered'
  rebill_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-rebill'
  rebill_failed_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-rebill-failure'
  search_indexing_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-searchindex'
  
nmi:
  username: 'demo'
  password: 'password'
  endpoint: 'https://secure.networkmerchants.com/api/transact.php'
  
shipping_providers:
  usps:
    user_id: '005SIXCR2114'
    password: '392VM80MW850'