-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsBNGltH7St/zRl1ZVKv4RZ1UF8GhbaZ/tb6JorXt8TSgCgYIKoZIzj0DAQehRANCAASRHyJdkFZz4Dzol/XWYgTsOrJkBGaUvrhYYVKa4nhNAbK+ecrh+/V0yML8Nnns6o1VgKdNcvpQRJTyke1ppYf1
-----END PRIVATE KEY-----