site_secret_jwt_key: 'ashdaiuwdaw9d0u197f02ji9ujoja90juahwi'
dynamodb:
  access_keys_table: 'access_keys'
  sessions_table: 'sessions'
  transactions_table: 'transactions'
  customers_table: 'customers'
  products_table: 'products'
  creditcards_table: 'creditcards'
  endpoint: 'http://localhost:8001'
nmi:
  username: 'demo'
  password: 'password'
  endpoint: 'https://secure.networkmerchants.com/api/transact.php'

