jwt:
  transaction_key: 'ashdaiuwdaw9d0u197f02ji9ujoja90juahwi'
  site_key: 'anwdadawdjaklwdlakd'
  development_bypass: 'deathstalker'
  
dynamodb:
  access_keys_table: 'access_keys'
  sessions_table: 'sessions'
  transactions_table: 'transactions'
  rebills_table: 'rebills'
  customers_table: 'customers'
  products_table: 'products'
  credit_cards_table: 'credit_cards'
  users_table: 'users'
  loadbalancers_table: 'loadbalancers'
  product_schedules_table: 'product_schedules'
  affiliates_table: 'affiliates'
  campaigns_table: 'campaigns'
  merchant_providers_table: 'merchant_providers'
  fulfillment_providers_table: 'fulfillment_providers'
  emails_table: 'emails'
  smtp_providers_table: 'smtp_providers'
  shipping_receipts_table: 'shipping_receipts'
  accounts_table: 'accounts'
  roles_table: 'roles'
  endpoint: 'http://localhost:8001'
  
lambda:
  endpoint: 'http://localhost:3000'
  function_names:
    deliveredtoarchive: 'sixtransaction-development-archivedelivered'
    shippedtodelivered: 'sixtransaction-development-confirmdelivered'
    pendingtoshipped: 'sixtransaction-development-confirmshipped'
    pendingfailedtopending: 'sixtransaction-development-shipproduct'
    holdtopending: 'sixtransaction-development-shipproduct'
    holdtoarchive: 'sixtransaction-development-archivehold'
    billtohold: 'sixtransaction-development-processbilling'
    recovertohold: 'sixtransaction-development-processbilling'
    createrebillstoarchive: 'sixtransaction-development-createrebills'
    recovertoarchive: 'sixtransaction-development-archiverecover'
    
sqs:
  bill_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-bill'
  recover_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-recover'
  hold_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-hold'
  pending_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-pending'
  pending_failed_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-pending-failed'
  shipped_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-shipped'
  delivered_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-delivered'
  rebill_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-rebill'
  rebill_failed_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-rebill-failure'
  
nmi:
  username: 'demo'
  password: 'password'
  endpoint: 'https://secure.networkmerchants.com/api/transact.php'
  
shipping_providers:
  usps:
    user_id: '005SIXCR2114'
    password: '392VM80MW850'

