jwt:
  issuer: 'https://api.sixcrm.com'
  development_bypass: 'deathstalker'
  site: #This is the key for all graph requests (AKA Six users)
    secret_key: 'pO9HJmVXzTOagNP-xW9Es8-s0HGQt28hqlvAPJx6e6rHeryvnyBGDn-LJn_80XdV'
    domain: ''
    expiration: 3600
  transaction: #This is the key for the transactional endpoint requests (AKA non-Six users...)
    secret_key: 'ashdaiuwdaw9d0u197f02ji9ujoja90juahwi'
    expiration: 3600
  #Technical Debt:  The site key may be deprecated...
  site_key: 'anwdadawdjaklwdlakd'

dynamodb:
  endpoint: 'http://localhost:8001'

lambda:
  endpoint: 'http://localhost:3000'
  function_names:
    deliveredtoarchive: 'sixtransaction-development-archivedelivered'
    shippedtodelivered: 'sixtransaction-development-confirmdelivered'
    pendingtoshipped: 'sixtransaction-development-confirmshipped'
    pendingfailedtopending: 'sixtransaction-development-shipproduct'
    holdtopending: 'sixtransaction-development-shipproduct'
    holdtoarchive: 'sixtransaction-development-archivehold'
    billtohold: 'sixtransaction-development-processbilling'
    recovertohold: 'sixtransaction-development-processbilling'
    createrebillstoarchive: 'sixtransaction-development-createrebills'
    recovertoarchive: 'sixtransaction-development-archiverecover'
    indextoarchive: 'sixtransaction-development-indexentities'
    forwardmessage_deliveredtoarchive: 'sixtransaction-development-deliveredtoarchive'
    forwardmessage_shippedtodelivered: 'sixtransaction-development-shippedtodelivered'
    forwardmessage_pendingtoshipped: 'sixtransaction-development-pendingtoshipped'
    forwardmessage_pendingfailedtopending: 'sixtransaction-development-pendingfailedtopending'
    forwardmessage_holdtopending: 'sixtransaction-development-holdtopending'
    forwardmessage_holdtoarchive: 'sixtransaction-development-holdtoarchive'
    forwardmessage_billtohold: 'sixtransaction-development-billtohold'
    forwardmessage_recovertohold: 'sixtransaction-development-recovertohold'
    forwardmessage_createrebillstoarchive: 'sixtransaction-development-rebilltoarchive'
    forwardmessage_recovertoarchive: 'sixtransaction-development-recovertoarchive'
    forwardmessage_indextoarchive: 'sixtransaction-development-indextoarchive'

shipping_providers:
  usps:
    user_id: '005SIXCR2114'
    password: '392VM80MW850'

redshift:
  user: 'admin'
  database: 'dev'
  password: 'Jagodica9'
  host: 'sixcrm-test.ch9ptr45aofu.us-east-1.redshift.amazonaws.com'
  port: 5439
  max: 10
  idleTimeoutMillis: 30000
  randomdata:
    staging_bucket: 'sixcrm-development-redshift/sixcrm-random-generator'
    interval: 300 #this is provided in seconds

notifications:
  apn:
    token_key: ''
    token_key_id: ''
    token_team_id: ''
    production: false

#Technical Debt:  Down the road, we may have numerous caching strategies and we will need to be able to configure them dynamically
cache:
  usecache: 1
  cachebuster: 'somerandomthing1236901cacdda'

elasticache:
  max_attempts: 3
  retry_time: 1800000
  endpoint: 'localhost'
  port: 6379

logging:
  loglevel: 2

aws:
  region: 'us-east-1'
  account: '068070110666'

kinesis:
  firehose:
    streams:
      transactions: 'six-development-transactions'
      events: 'six-development-events'
      activity: 'six-development-activity'
