jwt:
  development_bypass: 'deathstalker'
  auth0: #This is the key for all graph requests (AKA Six users)
    secret_key: 'pO9HJmVXzTOagNP-xW9Es8-s0HGQt28hqlvAPJx6e6rHeryvnyBGDn-LJn_80XdV'
    domain: ''
  transaction: #This is the key for the transactional endpoint requests (AKA non-Six users...)
    secret_key: 'ashdaiuwdaw9d0u197f02ji9ujoja90juahwi'
  #Technical Debt:  The site key may be deprecated...
  site_key: 'anwdadawdjaklwdlakd'

dynamodb:
  access_keys_table: 'access_keys'
  sessions_table: 'sessions'
  transactions_table: 'transactions'
  rebills_table: 'rebills'
  customers_table: 'customers'
  customer_notes_table: 'customer_notes'
  products_table: 'products'
  credit_cards_table: 'credit_cards'
  users_table: 'users'
  user_device_tokens_table: 'user_device_tokens'
  user_acls_table: 'useracls'
  user_settings_table: 'user_settings'
  loadbalancers_table: 'loadbalancers'
  product_schedules_table: 'product_schedules'
  affiliates_table: 'affiliates'
  campaigns_table: 'campaigns'
  merchant_providers_table: 'merchant_providers'
  fulfillment_providers_table: 'fulfillment_providers'
  email_templates_table: 'email_templates'
  smtp_providers_table: 'smtp_providers'
  shipping_receipts_table: 'shipping_receipts'
  accounts_table: 'accounts'
  roles_table: 'roles'
  ses_notifications_table: 'ses_notifications'
  notifications_table: 'notifications'
  notifications_read_table: 'notifications_read'
  notification_settings_table: 'notification_settings'
  endpoint: 'http://localhost:8001'

lambda:
  endpoint: 'http://localhost:3000'
  function_names:
    deliveredtoarchive: 'sixtransaction-development-archivedelivered'
    shippedtodelivered: 'sixtransaction-development-confirmdelivered'
    pendingtoshipped: 'sixtransaction-development-confirmshipped'
    pendingfailedtopending: 'sixtransaction-development-shipproduct'
    holdtopending: 'sixtransaction-development-shipproduct'
    holdtoarchive: 'sixtransaction-development-archivehold'
    billtohold: 'sixtransaction-development-processbilling'
    recovertohold: 'sixtransaction-development-processbilling'
    createrebillstoarchive: 'sixtransaction-development-createrebills'
    recovertoarchive: 'sixtransaction-development-archiverecover'
    indextoarchive: 'sixtransaction-development-indexentities'
    forwardmessage_deliveredtoarchive: 'sixtransaction-development-forwardmessage_archivedelivered'
    forwardmessage_shippedtodelivered: 'sixtransaction-development-forwardmessage_confirmdelivered'
    forwardmessage_pendingtoshipped: 'sixtransaction-development-forwardmessage_confirmshipped'
    forwardmessage_pendingfailedtopending: 'sixtransaction-development-forwardmessage_shipproduct'
    forwardmessage_holdtopending: 'sixtransaction-development-forwardmessage_shipproduct'
    forwardmessage_holdtoarchive: 'sixtransaction-development-forwardmessage_archivehold'
    forwardmessage_billtohold: 'sixtransaction-development-forwardmessage_processbilling'
    forwardmessage_recovertohold: 'sixtransaction-development-forwardmessage_processbilling'
    forwardmessage_createrebillstoarchive: 'sixtransaction-development-forwardmessage_createrebills'
    forwardmessage_recovertoarchive: 'sixtransaction-development-forwardmessage_archiverecover'
    forwardmessage_indextoarchive: 'sixtransaction-development-forwardmessage_indexentities'

sqs:
  bill_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-bill'
  bill_failed_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-bill-failed'
  recover_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-recover'
  hold_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-hold'
  pending_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-pending'
  pending_failed_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-pending-failed'
  shipped_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-shipped'
  delivered_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-delivered'
  rebill_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-rebill'
  rebill_failed_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-rebill-failure'
  search_indexing_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-searchindex'
  search_deindexing_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-searchdeindex'

nmi:
  username: 'demo'
  password: 'password'
  endpoint: 'https://secure.networkmerchants.com/api/transact.php'

shipping_providers:
  usps:
    user_id: '005SIXCR2114'
    password: '392VM80MW850'

redshift:
  user: 'admin'
  database: 'dev'
  password: 'Jagodica9'
  host: 'sixcrm-test.ch9ptr45aofu.us-east-1.redshift.amazonaws.com'
  port: 5439
  max: 10
  idleTimeoutMillis: 30000
  randomdata:
    staging_bucket: 'redshift-data-staging'
    interval: 300 #this is provided in seconds

notifications:
  apn:
    token_key: ''
    token_key_id: ''
    token_team_id: ''
    production: false

#Technical Debt:  Down the road, we may have numerous caching strategies and we will need to be able to configure them dynamically
cache:
  usecache: 1
  cachebuster: 'somerandomthing123'

elasticache:
  max_attempts: 3
  retry_time: 1800000
  endpoint: 'localhost'
  port: 6379

logging:
  loglevel: 2

kinesis:
  firehose:
    streams:
      transactions: 'six-development-transactions'
      events: 'six-development-events'
      activity: 'six-development-activity'
aws:
  region: 'us-east-1'
