jwt:
  transaction_key: 'ashdaiuwdaw9d0u197f02ji9ujoja90juahwi'
  site_key: 'anwdadawdjaklwdlakd'
  development_bypass: 'deathstalker'
dynamodb:
  access_keys_table: 'access_keys'
  sessions_table: 'sessions'
  transactions_table: 'transactions'
  customers_table: 'customers'
  products_table: 'products'
  credit_cards_table: 'credit_cards'
  users_table: 'users'
  loadbalancers_table: 'loadbalancers'
  product_schedules_table: 'product_schedules'
  affiliates_table: 'affiliates'
  campaigns_table: 'campaigns'
  merchant_providers_table: 'merchant_providers'
  fulfillment_providers_table: 'fulfillment_providers'
  endpoint: 'http://localhost:8001'
sqs:
  bill_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-bill'
  hold_queue_url: 'https://sqs.us-east-1.amazonaws.com/068070110666/development-hold'
nmi:
  username: 'demo'
  password: 'password'
  endpoint: 'https://secure.networkmerchants.com/api/transact.php'

