development:
  aws_account_id: '068070110666'
  branch_name: 'development'
staging:
  aws_account_id: '821071795213'
  branch_name: 'staging'
production:
  aws_account_id: '181111172466'
  branch_name: 'production'
local:
  local: true
local-docker:
  local: true
circle:
  local: true
