INSERT INTO {{TABLE_NAME}}
SELECT id,
       datetime,
       customer,
       creditcard,
       merchant_provider,
       campaign,
       affiliate,
       amount,
       processor_result,
       account,
       TYPE,
       subtype,
       product_schedule,
       subaffiliate_1,
       subaffiliate_2,
       subaffiliate_3,
       subaffiliate_4,
       subaffiliate_5,
       prepaid,
       RESULT,
       associated_transaction,
FROM f_transactions
WHERE 1=1
  AND datetime BETWEEN date_trunc('day', {{datetime}}) - interval '1 day' AND date_trunc('day',{{datetime}}) - interval '00:00:00.000001';
